alias ls='ls -hF --color=auto'
alias l='ls -lhF'
alias mv='advmv -i'
alias cp='advcp -gr'
alias touch='f(){mkdir -p $(dirname "$@"); touch "$@"}; f'
alias mkdir='mkdir -p'
alias ptpy='ptpython'
alias nano='nano --nonewlines'
alias curl='curl --location'
builtin alias -- -='what'
alias g=git
alias gep='git add . && git commit --amend --no-edit && git psh --force-with-lease'
alias gcp='f(){git add . && git cm "$*" && git psh};f'
alias activate='{test -d .venv && source .venv/bin/activate} || {test -d venv && source venv/bin/activate}'