#!/usr/bin/env bash

if command -v wl-paste >/dev/null 2>&1; then
	function read-clipboard() {
		local clipboard="$1"
		local flag="$([[ "$clipboard" == "primary" ]] && echo "--primary" || true)"
		wl-paste --no-newline $flag
	}
elif command -v xclip >/dev/null 2>&1; then
	function read-clipboard() {
		xclip -o -selection "$1"
	}
fi

read-clipboard "$1" | tmux load-buffer -
if [[ "$PASTE" != "no" ]]; then
	tmux paste-buffer
fi